name: myapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6 #USED
  animations: ^2.0.11 #USED
  hexcolor: ^3.0.1 #USED
  get: ^4.6.5 #USED
  flutter_svg: ^2.0.10+1 #USED
  carousel_slider: ^4.2.1 #USED
  smooth_page_indicator: ^1.1.0 #USED
  flutter_advanced_drawer: ^1.3.6 #USED
  http: ^1.2.1 #USED
  shared_preferences: ^2.2.2 #USED
  url_launcher: ^6.3.0
  provider: ^6.1.2
  youtube_explode_dart: ^2.2.1 #USED
  just_audio: ^0.9.37 #USED
  palette_generator: ^0.3.3+4
  flutter_local_notifications: ^14.0.0 #USED
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  # IMAGES
    - assets/images/logo.png
    - assets/images/google.svg
    - assets/images/onboardingimages/ads.svg
    - assets/images/onboardingimages/control.svg
    - assets/images/onboardingimages/playlist.svg
    - assets/images/onboardingimages/quality.svg
    - assets/images/onboardingimages/welcome.svg


    # FONTS
    - assets/fonts/
  fonts:
    - family: broken
      fonts:
        - asset: assets/fonts/broken.ttf
    - family: broken_filled
      fonts:
        - asset: assets/fonts/broken_filled.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf
